services:
  php:
    container_name: setup-symfony-php
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile
    restart: unless-stopped
    tty: true
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - setup-symfony_network

  nginx:
    container_name: setup-symfony-nginx
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    ports:
      - '8080:80'
      - '443:443'
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - setup-symfony_network

  database:
    container_name: setup-symfony-database
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    tty: true
    volumes:
      - database-data:/var/lib/mysql/
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - setup-symfony_network
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: ${MYSQL_DB:-setup-symfony}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD:-setup-symfony}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-setup-symfony}
      MYSQL_USER: ${MYSQL_USER:-setup-symfony}

networks:
  setup-symfony_network:
    driver: bridge

volumes:
  database-data:
    driver: local